### ISSUE TITLE
"TaskManager" testing technique

### ISSUE THREAD

**Issue by PaddySmalls** [slipke/Zeitfresser#10]
- Blackbox tests, whitebox tests, equivalence classes?
- Which technique and why?
- Define equivalence classes if any

**Comment by PaddySmalls** [comment]
Ansatz mit Blackbox-Tests und Äquivalenzklassen:

`void addTasktWithName(String taskName)`

-   erlaubte ÄK1: Zeichenketten, die aus mindestens einem Zeichen bestehen
-   nicht erlaubte ÄK1: null oder leere Zeichenkette (Exception)

`List<String> getExistentTaskNamesAsList()`

- keine Parameter

`void startTask(Task task)`

- erlaubte ÄK1: Instanz der Klasse Task
- nicht erlaubte ÄK1: null (Exception)

`void stopTask(Task task)`

- erlaubte ÄK1: Instanz der Klasse Task
- nicht erlaubte ÄK1: null (Exception)

`boolean isActiveTask(Task task)`

- erlaubte ÄK1: Instanz der Klasse Task
- nicht erlaubte ÄK1: null (Exception)

`float getTotalDurationForTask(Task task)`

- erlaubte ÄK1: Instanz der Klasse Task
- nicht erlaubte ÄK1: null (Exception)

**Comment by apophizzz** [comment]
Abgehakt.
