### ISSUE TITLE
Integrationstests haben scheinbar Seiteneffekte

### ISSUE THREAD

**Issue by PaddySmalls** [slipke/Zeitfresser#18]
@slipke Die Integrationstests in der Klasse _TaskManagerTest_ scheinen Seiteneffekte zu haben. Wenn man die Tests mehrmals hintereinander ausführt, schlagen bei mir zufällig einzelne Tests fehl. Der Test _testGetFilteredTasksWithFrom_ läuft gar nicht durch, wenn er einzeln ausgeführt wird. 

![fail](https://cloud.githubusercontent.com/assets/12052783/23122648/6d679ca8-f765-11e6-8f0b-de4df4e8ca8a.png)

Zusätzlich sollten wir die Integrationstests in eine separate Klasse packen, damit wir sie separat ausführen können. 
Was denkst du dazu? Hast du eine Idee, woher das kommen könnte?

**Comment by slipke** [comment]
Ich wars nicht! :P

Ich hab das auch schon festgestellt, konnte mir das auf den ersten Blick aber auch nicht erklären (dachte eigentlich, das Problem hätte sich von selbst erledigt, da bei mir nach dem 2. Mal alle Tests durchliefen). 

Das Ganze ist doch eigentlich auch noch kein Integrationstest (oder hab ich das falsch verstanden?) - da hier keine Datenbank im Spiel ist. Ich hatte eigentlich vor, noch einen Intetrationstest zu schreiben (ein Test, der die komplette Datenbank mit nutzt und auch die Originalklasse _DbTaskManager_, nicht den _TaskManagerDummy_)

**Comment by PaddySmalls** [comment]
Kein Problem, fiel mir gerade bei der Ausführung nur so auf :)
Aus meiner Sicht sind das Integrationstests, weil ja z.B. über die Dummy-Task-Objekte die Methoden der Klasse _Task_ aufgerufen werden, z.B. _hasRecordsAfter(Date date)_ etc. Deshalb dachte ich, du hättest das absichtlich so als Integrationstest implementiert. Das sollten wir dann wenn's geht am besten auch über Mock-Objekte lösen. Kann ich mir aber gerne nochmal anschauen, da ich gerade eh an der Klasse dran bin, wegen der TDD-Geschichte.

**Comment by PaddySmalls** [comment]
Die Dummys wurden durch Mocks ersetzt, seither laufen die Test wie geschmiert. Ich mach hier dann mal das Licht aus :)
