### ISSUE TITLE
Vereinfachung der Logik für start() und stopp() in der Record-Klasse

### ISSUE THREAD

**Issue by apophizzz** [slipke/Zeitfresser#19]
@bh051 Ich habe eben angefangen, nochmal über die Record-Tests drüberzuschauen. Mir sind bei den Methoden für _start()_ und _stop()_ spontan Möglichkeiten eingefallen, die die Logik und damit auch die Tests wesentlich einfacher machen. Zum Beispiel in der start-Methode:

``` java
public void start() {
    if (start != null && end != null) {
      if (start.getTime() > end.getTime()) {
        /* if start time is even bigger than end time then
           start was called twice */
        throw new IllegalStateException();
      }
    } else if (start != null && end == null) {
      // record was started twice, but not stopped
      throw new IllegalStateException();
    }
    start = new Date();
  }
```

Die Vergleiche von Start- und Endzeit können wir uns ja sparen, wenn wir uns einfach an die erlaubten Zustandsübergänge halten:

```java
  public void start() {
    if (start != null) {
      // Record wurde bereits gestartet.
      throw new IllegalStateException("Record has already been started.");
    }
    // Record wurde noch nicht gestartet. Setze Startdatum bzw. -zeit.
    start = new Date();
  }
```

Bei _stop()_ würde das ganz ähnlich aussehen. Das müsste doch eigentlich schon genügen oder? Ich frage nur deshalb, weil das Auswirkungen auf das Zustandsdiagramm für den Record haben sollte. Aber ist kein Problem, da würd ich dann spätestens Freitagvormittag danach schauen. Sag einfach mal deine Meinung dazu, du hast dir bei der Implementierung ja sicher auch was dabei gedacht.

**Comment by bh051** [comment]
@PaddySmalls ja ich glaube so ähnlich hatte ich das zunächst auch. Als ich dann das damalige Zustandsdiagramm mit der Frau Dörsam besprochen habe, kamen wir zu dem Entschluss, dass ein bereits gestarteter Record nicht nochmal gestartet werden können soll. Genau wie ein gestoppter oder noch nicht gestarteter Record nicht gestoppt werden können soll. Und das man das in den Tests aufnehmen sollte.  

Ich habe eigentlich nur die Tests geschrieben und dann den Code angepasst bis alle Test geklappt haben. Das wäre auch ein gutes Beispiel für ein Vorteil von Unit Tests. Müsste ich auch so in der Doku geschrieben haben.

Aber vllt gibt es echt eine einfachere Möglichkeit. Ich schau mir das heute mittag auch nochmal an.

**Comment by PaddySmalls** [comment]
>  kamen wir zu dem Entschluss, dass ein bereits gestarteter Record nicht nochmal gestartet werden können soll

Dann müsste dieser Test ja eigentlich auf ne _IllegalStateException_ prüfen oder? 

```java
@Test
  public void testStartStoppedRecord() {
    record.start();
    timeout();

    record.stop();
    long end = getEndFieldValue().getTime();

    timeout();
    record.start();
    long start = getStartFieldValue().getTime();

    assertTrue(start >= end);
  }
```

Nur zum Verständnis: Das heißt ein Record wird genau einmal gestartet und gestoppt und kann danach auch __nicht nochmal__ neu gestartet werden? Oder anders formuliert: Sobald _start_ und _end_ gesetzt sind, befindet sich ein Record also im "Endzustand"?

**Comment by PaddySmalls** [comment]
Wurde größtenteils mit Commit fbb4a44c36423557667df4640558381235a09d2c überarbeitet und ist somit erledigt.
