### ISSUE TITLE
Create state diagram for class "Record"

### ISSUE THREAD

**Issue by PaddySmalls** [slipke/Zeitfresser#7]

**Comment by bh051** [comment]
Ich habe mal begonnen ein Zustandsdiagramm für die Record Klasse zu zeichnen. Habe das mit draw.io gemacht. Die XML-Datei dafür liegt in unserem drive-Ordner: https://drive.google.com/open?id=0B8VCzD0ply38bGxfdFFXaFVISG8
(https://cloud.githubusercontent.com/assets/18190769/20671254/e6aebff4-b57c-11e6-92ce-18b7bd400ec9.png)
